// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Header$App from "./components/Header.bs.js";
import * as HomePage$App from "./pages/HomePage.bs.js";
import * as ErrorPage$App from "./pages/ErrorPage.bs.js";
import * as SignInPage$App from "./pages/SignInPage.bs.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var list = [
    "tim.com",
    "whatever.com",
    "fake.com",
    "google.com",
    "fpse.com",
    "winner.com",
    "finalproject.com",
    "greatest.com"
  ];
  var match = url.path;
  var tmp;
  tmp = match ? (
      match.hd === "home" ? (
          match.tl ? React.createElement(ErrorPage$App.make, {}) : React.createElement(HomePage$App.make, {
                  list: list
                })
        ) : React.createElement(ErrorPage$App.make, {})
    ) : React.createElement(SignInPage$App.make, {});
  return React.createElement("div", {
              className: "w-screen h-screen flex flex-row justify-center"
            }, React.createElement("div", {
                  className: "w-frame h-full bg-white"
                }, React.createElement(Header$App.make, {}), tmp));
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
