// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function ErrorPage(Props) {
  return React.createElement("div", {
              className: "bg-frame bg-rose-400 h-screen flex items-center justify-center"
            }, React.createElement("button", {
                  onClick: (function ($$event) {
                      RescriptReactRouter.push("/home");
                    })
                }, "Go to Home Page"));
}

var make = ErrorPage;

export {
  make ,
}
/* react Not a pure module */
