// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as UrlList$App from "../components/UrlList.bs.js";

function HomePage(Props) {
  var list = Props.list;
  var match = React.useState(function () {
        return "";
      });
  var setText = match[1];
  var handleInputChange = function ($$event) {
    var value = $$event.currentTarget.value;
    Curry._1(setText, (function (param) {
            return value;
          }));
  };
  return React.createElement("div", {
              className: "bg-rose-400 h-screen flex flex-col items-center justify-around p-40"
            }, React.createElement("div", {
                  className: "bg-rose-400 flex flex-row"
                }, React.createElement("input", {
                      type: "text",
                      value: match[0],
                      onChange: handleInputChange
                    }), React.createElement("button", {
                      className: "bg-gray-400"
                    }, "Create Tiny URL")), React.createElement(UrlList$App.make, {
                  list: list
                }));
}

var make = HomePage;

export {
  make ,
}
/* react Not a pure module */
