// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function UrlList(Props) {
  var list = Props.list;
  var urls = Belt_Array.map(list, (function (url) {
          return React.createElement("li", undefined, url);
        }));
  return React.createElement("button", {
              onClick: (function ($$event) {
                  RescriptReactRouter.push("/whatever");
                })
            }, urls);
}

var make = UrlList;

export {
  make ,
}
/* react Not a pure module */
